/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_movlad_pcl_SampleConsensus */

#ifndef _Included_com_movlad_pcl_SampleConsensus
#define _Included_com_movlad_pcl_SampleConsensus
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_movlad_pcl_SampleConsensus
 * Method:    setSampleConsensusModel
 * Signature: (Lde/i3mainz/pcl/SampleConsensusModel;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_SampleConsensus_nSetSampleConsensusModel
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_movlad_pcl_SampleConsensus
 * Method:    getDistanceThreshold
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_movlad_pcl_SampleConsensus_getDistanceThreshold
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_SampleConsensus
 * Method:    setDistanceThreshold
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_SampleConsensus_setDistanceThreshold
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_movlad_pcl_SampleConsensus
 * Method:    getMaxIterations
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_movlad_pcl_SampleConsensus_getMaxIterations
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_SampleConsensus
 * Method:    setMaxIterations
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_SampleConsensus_setMaxIterations
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_movlad_pcl_SampleConsensus
 * Method:    getProbability
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_movlad_pcl_SampleConsensus_getProbability
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_SampleConsensus
 * Method:    setProbability
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_SampleConsensus_setProbability
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_movlad_pcl_SampleConsensus
 * Method:    refineModel
 * Signature: (DI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_movlad_pcl_SampleConsensus_refineModel
  (JNIEnv *, jobject, jdouble, jint);

/*
 * Class:     com_movlad_pcl_SampleConsensus
 * Method:    nGetInliners
 * Signature: (Lde/i3mainz/pcl/PointCloud;Lde/i3mainz/pcl/PointCloud;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_SampleConsensus_nGetInliners
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
