/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_movlad_pcl_io_PointCloud3dWriter */

#ifndef _Included_com_movlad_pcl_io_PointCloud3dWriter
#define _Included_com_movlad_pcl_io_PointCloud3dWriter
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     com_movlad_pcl_io_PointCloud3dWriter
 * Method:    writePCD
 * Signature: (Ljava/lang/String;Lde/i3mainz/pcl/PointCloud;Z)V
 */
  JNIEXPORT void JNICALL Java_com_movlad_pcl_io_PointCloud3dWriter_writePCD(JNIEnv *, jobject, jstring, jobject, jboolean);

  /*
 * Class:     com_movlad_pcl_io_PointCloud3dWriter
 * Method:    writePLY
 * Signature: (Ljava/lang/String;Lde/i3mainz/pcl/PointCloud;Z)V
 */
  JNIEXPORT void JNICALL Java_com_movlad_pcl_io_PointCloud3dWriter_writePLY(JNIEnv *, jobject, jstring, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
