/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_movlad_pcl_PointCloud3di */

#ifndef _Included_com_movlad_pcl_PointCloud3di
#define _Included_com_movlad_pcl_PointCloud3di
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_movlad_pcl_PointCloud3di
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_PointCloud3di_alloc
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_PointCloud3di
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_PointCloud3di_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_PointCloud3di
 * Method:    nGet
 * Signature: (ILde/i3mainz/pcl/Point3d;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_PointCloud3di_nGet
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_movlad_pcl_PointCloud3di
 * Method:    add
 * Signature: (Lde/i3mainz/pcl/Point3d;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_PointCloud3di_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_movlad_pcl_PointCloud3di
 * Method:    remove
 * Signature: (Lde/i3mainz/pcl/Point3d;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_PointCloud3di_remove
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_movlad_pcl_PointCloud3di
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_PointCloud3di_clear
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_PointCloud3di
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_movlad_pcl_PointCloud3di_size
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_PointCloud3di
 * Method:    isOrganized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_movlad_pcl_PointCloud3di_isOrganized
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
