/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_movlad_pcl_Matrix4f */

#ifndef _Included_com_movlad_pcl_Matrix4f
#define _Included_com_movlad_pcl_Matrix4f
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_movlad_pcl_Matrix4f
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Matrix4f_alloc
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Matrix4f
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Matrix4f_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Matrix4f
 * Method:    nGet
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_com_movlad_pcl_Matrix4f_nGet
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_movlad_pcl_Matrix4f
 * Method:    nSet
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Matrix4f_nSet
  (JNIEnv *, jobject, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
