/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_movlad_pcl_SampleConsensusModelSphere */

#ifndef _Included_com_movlad_pcl_SampleConsensusModelSphere
#define _Included_com_movlad_pcl_SampleConsensusModelSphere
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_movlad_pcl_SampleConsensusModelSphere
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_SampleConsensusModelSphere_alloc
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_SampleConsensusModelSphere
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_SampleConsensusModelSphere_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
