/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_movlad_pcl_registration_GeneralizedIterativeClosestPoint */

#ifndef _Included_com_movlad_pcl_registration_GeneralizedIterativeClosestPoint
#define _Included_com_movlad_pcl_registration_GeneralizedIterativeClosestPoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_movlad_pcl_registration_GeneralizedIterativeClosestPoint
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_GeneralizedIterativeClosestPoint_alloc
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_registration_GeneralizedIterativeClosestPoint
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_GeneralizedIterativeClosestPoint_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_registration_GeneralizedIterativeClosestPoint
 * Method:    setInputSource
 * Signature: (Lcom/movlad/pcl/PointCloud3d;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_GeneralizedIterativeClosestPoint_setInputSource
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_movlad_pcl_registration_GeneralizedIterativeClosestPoint
 * Method:    setInputTarget
 * Signature: (Lcom/movlad/pcl/PointCloud3d;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_GeneralizedIterativeClosestPoint_setInputTarget
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_movlad_pcl_registration_GeneralizedIterativeClosestPoint
 * Method:    setMaximumIterations
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_GeneralizedIterativeClosestPoint_setMaximumIterations
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_movlad_pcl_registration_GeneralizedIterativeClosestPoint
 * Method:    setRotationEpsilon
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_GeneralizedIterativeClosestPoint_setRotationEpsilon
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_movlad_pcl_registration_GeneralizedIterativeClosestPoint
 * Method:    estimateRigidTransformationBFGS
 * Signature: (Lcom/movlad/pcl/PointCloud3d;[ILcom/movlad/pcl/PointCloud3d;[ILcom/movlad/pcl/Matrix4;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_GeneralizedIterativeClosestPoint_estimateRigidTransformationBFGS
  (JNIEnv *, jobject, jobject, jintArray, jobject, jintArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
