/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_movlad_pcl_NormalCloud */

#ifndef _Included_com_movlad_pcl_NormalCloud
#define _Included_com_movlad_pcl_NormalCloud
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_movlad_pcl_NormalCloud
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_NormalCloud_alloc
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_NormalCloud
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_NormalCloud_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_NormalCloud
 * Method:    nGet
 * Signature: (ILde/i3mainz/pcl/Normal;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_NormalCloud_nGet
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_movlad_pcl_NormalCloud
 * Method:    add
 * Signature: (Lde/i3mainz/pcl/Normal;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_NormalCloud_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_movlad_pcl_NormalCloud
 * Method:    remove
 * Signature: (Lde/i3mainz/pcl/Normal;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_NormalCloud_remove
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_movlad_pcl_NormalCloud
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_NormalCloud_clear
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_NormalCloud
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_movlad_pcl_NormalCloud_size
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_NormalCloud
 * Method:    isOrganized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_movlad_pcl_NormalCloud_isOrganized
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
