/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_movlad_pcl_registration_IterativeClosestPoint */

#ifndef _Included_com_movlad_pcl_registration_IterativeClosestPoint
#define _Included_com_movlad_pcl_registration_IterativeClosestPoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_movlad_pcl_registration_IterativeClosestPoint
 * Method:    setInputSource
 * Signature: (Lcom/movlad/pcl/PointCloud3d;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_IterativeClosestPoint_setInputSource
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_movlad_pcl_registration_IterativeClosestPoint
 * Method:    setInputTarget
 * Signature: (Lcom/movlad/pcl/PointCloud3d;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_IterativeClosestPoint_setInputTarget
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_movlad_pcl_registration_IterativeClosestPoint
 * Method:    setMaximumIterations
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_IterativeClosestPoint_setMaximumIterations
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_movlad_pcl_registration_IterativeClosestPoint
 * Method:    setMaxCorrespondenceDistance
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_IterativeClosestPoint_setMaxCorrespondenceDistance
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_movlad_pcl_registration_IterativeClosestPoint
 * Method:    setTransformationEpsilon
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_IterativeClosestPoint_setTransformationEpsilon
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_movlad_pcl_registration_IterativeClosestPoint
 * Method:    setEuclideanFitnessEpsilon
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_IterativeClosestPoint_setEuclideanFitnessEpsilon
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_movlad_pcl_registration_IterativeClosestPoint
 * Method:    align
 * Signature: (Lcom/movlad/pcl/PointCloud3d;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_IterativeClosestPoint_align
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_movlad_pcl_registration_IterativeClosestPoint
 * Method:    getFinalTransformation
 * Signature: (Lcom/movlad/pcl/Matrix4;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_registration_IterativeClosestPoint_getFinalTransformation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_movlad_pcl_registration_IterativeClosestPoint
 * Method:    hasConverged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_movlad_pcl_registration_IterativeClosestPoint_hasConverged
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
