/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_movlad_pcl_SampleConsensusModelCone */

#ifndef _Included_com_movlad_pcl_SampleConsensusModelCone
#define _Included_com_movlad_pcl_SampleConsensusModelCone
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_movlad_pcl_SampleConsensusModelCone
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_SampleConsensusModelCone_alloc
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_SampleConsensusModelCone
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_SampleConsensusModelCone_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_SampleConsensusModelCone
 * Method:    getNormalDistanceWeight
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_movlad_pcl_SampleConsensusModelCone_getNormalDistanceWeight
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_SampleConsensusModelCone
 * Method:    setNormalDistanceWeight
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_SampleConsensusModelCone_setNormalDistanceWeight
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_movlad_pcl_SampleConsensusModelCone
 * Method:    nGetInputNormals
 * Signature: (Lde/i3mainz/pcl/NormalCloud;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_SampleConsensusModelCone_nGetInputNormals
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_movlad_pcl_SampleConsensusModelCone
 * Method:    setInputNormals
 * Signature: (Lde/i3mainz/pcl/NormalCloud;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_SampleConsensusModelCone_setInputNormals
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
