/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_movlad_pcl_Normal */

#ifndef _Included_com_movlad_pcl_Normal
#define _Included_com_movlad_pcl_Normal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_movlad_pcl_Normal
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Normal_alloc
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Normal
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Normal_close
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Normal
 * Method:    getX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_movlad_pcl_Normal_getX
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Normal
 * Method:    setX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Normal_setX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_movlad_pcl_Normal
 * Method:    getY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_movlad_pcl_Normal_getY
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Normal
 * Method:    setY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Normal_setY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_movlad_pcl_Normal
 * Method:    getZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_movlad_pcl_Normal_getZ
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Normal
 * Method:    setZ
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Normal_setZ
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_movlad_pcl_Normal
 * Method:    getCurvature
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_movlad_pcl_Normal_getCurvature
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
