/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_movlad_pcl_SampleConsensusModel */

#ifndef _Included_com_movlad_pcl_SampleConsensusModel
#define _Included_com_movlad_pcl_SampleConsensusModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_movlad_pcl_SampleConsensusModel
 * Method:    setInputCloud
 * Signature: (Lde/i3mainz/pcl/PointCloud3d;)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_SampleConsensusModel_setInputCloud
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_movlad_pcl_SampleConsensusModel
 * Method:    getSampleSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_movlad_pcl_SampleConsensusModel_getSampleSize
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_SampleConsensusModel
 * Method:    computeVariance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_movlad_pcl_SampleConsensusModel_computeVariance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
