/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_movlad_pcl_Point3d */

#ifndef _Included_com_movlad_pcl_Point3d
#define _Included_com_movlad_pcl_Point3d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Point3d_alloc
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Point3d_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    getX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_movlad_pcl_Point3d_getX
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    setX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Point3d_setX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    getY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_movlad_pcl_Point3d_getY
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    setY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Point3d_setY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    getZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_movlad_pcl_Point3d_getZ
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    setZ
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Point3d_setZ
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    getR
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_movlad_pcl_Point3d_getR
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    setR
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Point3d_setR
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    getG
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_movlad_pcl_Point3d_getG
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    setG
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Point3d_setG
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    getB
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_movlad_pcl_Point3d_getB
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    setB
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Point3d_setB
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_movlad_pcl_Point3d
 * Method:    getRGB
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_movlad_pcl_Point3d_getRGB
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
