/* DO NOT EDIT THIS FILE - it is machine generated */

#include "/usr/java/jdk-11.0.2/include/jni.h"
#include "/usr/java/jdk-11.0.2/include/linux/jni_md.h"

/* Header for class com_movlad_pcl_Point3di */

#ifndef _Included_com_movlad_pcl_Point3di
#define _Included_com_movlad_pcl_Point3di
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_movlad_pcl_Point3di
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Point3di_alloc
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Point3di
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Point3di_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Point3di
 * Method:    getX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_movlad_pcl_Point3di_getX
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Point3di
 * Method:    setX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Point3di_setX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_movlad_pcl_Point3di
 * Method:    getY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_movlad_pcl_Point3di_getY
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Point3di
 * Method:    setY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Point3di_setY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_movlad_pcl_Point3di
 * Method:    getZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_movlad_pcl_Point3di_getZ
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Point3di
 * Method:    setZ
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Point3di_setZ
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_movlad_pcl_Point3dii
 * Method:    getI
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_movlad_pcl_Point3di_getI
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_Point3di
 * Method:    setI
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_Point3di_setI
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
