/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_SampleConsensusModelLine */

#ifndef _Included_de_i3mainz_pcl_SampleConsensusModelLine
#define _Included_de_i3mainz_pcl_SampleConsensusModelLine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_SampleConsensusModelLine
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_SampleConsensusModelLine_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_SampleConsensusModelLine
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_SampleConsensusModelLine_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
