/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_PointCloud3DC */

#ifndef _Included_de_i3mainz_pcl_PointCloud3DC
#define _Included_de_i3mainz_pcl_PointCloud3DC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_PointCloud3DC
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3DC_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3DC
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3DC_dispose
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3DC
 * Method:    isOrganized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_i3mainz_pcl_PointCloud3DC_isOrganized
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3DC
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_i3mainz_pcl_PointCloud3DC_size
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3DC
 * Method:    add
 * Signature: (Lde/i3mainz/pcl/Point3DC;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3DC_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3DC
 * Method:    remove
 * Signature: (Lde/i3mainz/pcl/Point3DC;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3DC_remove
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3DC
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3DC_clear
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3DC
 * Method:    nGet
 * Signature: (ILde/i3mainz/pcl/Point3DC;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3DC_nGet
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
