/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_io_Cloud3dWriter */

#ifndef _Included_de_i3mainz_pcl_io_Cloud3dWriter
#define _Included_de_i3mainz_pcl_io_Cloud3dWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_io_Cloud3dWriter
 * Method:    writePCD
 * Signature: (Ljava/lang/String;Lde/i3mainz/pcl/PointCloud3d;Z)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_io_Cloud3dWriter_writePCD
  (JNIEnv *, jobject, jstring, jobject, jboolean);

/*
 * Class:     de_i3mainz_pcl_io_Cloud3dWriter
 * Method:    writePLY
 * Signature: (Ljava/lang/String;Lde/i3mainz/pcl/PointCloud3d;Z)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_io_Cloud3dWriter_writePLY
  (JNIEnv *, jobject, jstring, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
