/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_visualization_SimpleVisualizer */

#ifndef _Included_de_i3mainz_pcl_visualization_SimpleVisualizer
#define _Included_de_i3mainz_pcl_visualization_SimpleVisualizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_visualization_SimpleVisualizer
 * Method:    addPointCloud
 * Signature: (Lde/i3mainz/pcl/PointCloud;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_i3mainz_pcl_visualization_SimpleVisualizer_addPointCloud
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     de_i3mainz_pcl_visualization_SimpleVisualizer
 * Method:    addPointCloudNormals
 * Signature: (Lde/i3mainz/pcl/PointCloud;Lde/i3mainz/pcl/PointCloudN;IFLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_i3mainz_pcl_visualization_SimpleVisualizer_addPointCloudNormals
  (JNIEnv *, jobject, jobject, jobject, jint, jfloat, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
