/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_PointCloud3d */

#ifndef _Included_de_i3mainz_pcl_PointCloud3d
#define _Included_de_i3mainz_pcl_PointCloud3d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_PointCloud3d
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3d_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3d
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3d_dispose
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3d
 * Method:    nGet
 * Signature: (ILde/i3mainz/pcl/Point3d;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3d_nGet
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3d
 * Method:    add
 * Signature: (Lde/i3mainz/pcl/Point3d;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3d_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3d
 * Method:    remove
 * Signature: (Lde/i3mainz/pcl/Point3d;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3d_remove
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3d
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3d_clear
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3d
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_i3mainz_pcl_PointCloud3d_size
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3d
 * Method:    isOrganized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_i3mainz_pcl_PointCloud3d_isOrganized
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
