/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_SampleConsensusModelSphere */

#ifndef _Included_de_i3mainz_pcl_SampleConsensusModelSphere
#define _Included_de_i3mainz_pcl_SampleConsensusModelSphere
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_SampleConsensusModelSphere
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_SampleConsensusModelSphere_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_SampleConsensusModelSphere
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_SampleConsensusModelSphere_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
