/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_RandomSampleConsensus */

#ifndef _Included_de_i3mainz_pcl_RandomSampleConsensus
#define _Included_de_i3mainz_pcl_RandomSampleConsensus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_RandomSampleConsensus
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_RandomSampleConsensus_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_RandomSampleConsensus
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_RandomSampleConsensus_dispose
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_RandomSampleConsensus
 * Method:    computeModel
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_i3mainz_pcl_RandomSampleConsensus_computeModel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
