/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_NormalEstimation */

#ifndef _Included_de_i3mainz_pcl_NormalEstimation
#define _Included_de_i3mainz_pcl_NormalEstimation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_NormalEstimation
 * Method:    compute
 * Signature: (Lde/i3mainz/pcl/PointCloud3d;FLde/i3mainz/pcl/NormalCloud;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_NormalEstimation_compute
  (JNIEnv *, jobject, jobject, jfloat, jobject);

#ifdef __cplusplus
}
#endif
#endif
