/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_PointCloud3D */

#ifndef _Included_de_i3mainz_pcl_PointCloud3D
#define _Included_de_i3mainz_pcl_PointCloud3D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_PointCloud3D
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3D_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3D
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3D_dispose
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3D
 * Method:    isOrganized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_i3mainz_pcl_PointCloud3D_isOrganized
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3D
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_i3mainz_pcl_PointCloud3D_size
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3D
 * Method:    add
 * Signature: (Lde/i3mainz/pcl/Point3D;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3D_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3D
 * Method:    remove
 * Signature: (Lde/i3mainz/pcl/Point3D;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3D_remove
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3D
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3D_clear
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3D
 * Method:    nGet
 * Signature: (ILde/i3mainz/pcl/Point3D;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3D_nGet
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
