/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_Point3DC */

#ifndef _Included_de_i3mainz_pcl_Point3DC
#define _Included_de_i3mainz_pcl_Point3DC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_Point3DC
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3DC_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3DC
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3DC_dispose
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3DC
 * Method:    getZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_i3mainz_pcl_Point3DC_getZ
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3DC
 * Method:    getR
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_i3mainz_pcl_Point3DC_getR
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3DC
 * Method:    getG
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_i3mainz_pcl_Point3DC_getG
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3DC
 * Method:    getB
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_i3mainz_pcl_Point3DC_getB
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3DC
 * Method:    getRGB
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_i3mainz_pcl_Point3DC_getRGB
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3DC
 * Method:    setR
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3DC_setR
  (JNIEnv *, jobject, jshort);

/*
 * Class:     de_i3mainz_pcl_Point3DC
 * Method:    setG
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3DC_setG
  (JNIEnv *, jobject, jshort);

/*
 * Class:     de_i3mainz_pcl_Point3DC
 * Method:    setB
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3DC_setB
  (JNIEnv *, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
