/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_Point3dColorN */

#ifndef _Included_de_i3mainz_pcl_Point3dColorN
#define _Included_de_i3mainz_pcl_Point3dColorN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_Point3dColorN
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3dColorN_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3dColorN
 * Method:    getNormalX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_i3mainz_pcl_Point3dColorN_getNormalX
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3dColorN
 * Method:    setNormalX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3dColorN_setNormalX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_i3mainz_pcl_Point3dColorN
 * Method:    getNormalY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_i3mainz_pcl_Point3dColorN_getNormalY
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3dColorN
 * Method:    setNormalY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3dColorN_setNormalY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_i3mainz_pcl_Point3dColorN
 * Method:    getNormalZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_i3mainz_pcl_Point3dColorN_getNormalZ
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3dColorN
 * Method:    setNormalZ
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3dColorN_setNormalZ
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
