/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_io_Cloud3DReader */

#ifndef _Included_de_i3mainz_pcl_io_Cloud3DReader
#define _Included_de_i3mainz_pcl_io_Cloud3DReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_io_Cloud3DReader
 * Method:    readPCD
 * Signature: (Ljava/lang/String;Lde/i3mainz/pcl/PointCloud3D;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_io_Cloud3DReader_readPCD
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     de_i3mainz_pcl_io_Cloud3DReader
 * Method:    readPLY
 * Signature: (Ljava/lang/String;Lde/i3mainz/pcl/PointCloud3D;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_io_Cloud3DReader_readPLY
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
