/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_Point3D */

#ifndef _Included_de_i3mainz_pcl_Point3D
#define _Included_de_i3mainz_pcl_Point3D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_Point3D
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3D_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3D
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3D_dispose
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3D
 * Method:    getX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_i3mainz_pcl_Point3D_getX
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3D
 * Method:    getY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_i3mainz_pcl_Point3D_getY
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3D
 * Method:    getZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_i3mainz_pcl_Point3D_getZ
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3D
 * Method:    setX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3D_setX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_i3mainz_pcl_Point3D
 * Method:    setY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3D_setY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_i3mainz_pcl_Point3D
 * Method:    setZ
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3D_setZ
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
