/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_SampleConsensusModelCylinder */

#ifndef _Included_de_i3mainz_pcl_SampleConsensusModelCylinder
#define _Included_de_i3mainz_pcl_SampleConsensusModelCylinder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_SampleConsensusModelCylinder
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_SampleConsensusModelCylinder_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_SampleConsensusModelCylinder
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_SampleConsensusModelCylinder_dispose
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_SampleConsensusModelCylinder
 * Method:    getNormalDistanceWeight
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_de_i3mainz_pcl_SampleConsensusModelCylinder_getNormalDistanceWeight
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_SampleConsensusModelCylinder
 * Method:    setNormalDistanceWeight
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_SampleConsensusModelCylinder_setNormalDistanceWeight
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     de_i3mainz_pcl_SampleConsensusModelCylinder
 * Method:    nGetInputNormals
 * Signature: (Lde/i3mainz/pcl/NormalCloud;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_SampleConsensusModelCylinder_nGetInputNormals
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_i3mainz_pcl_SampleConsensusModelCylinder
 * Method:    setInputNormals
 * Signature: (Lde/i3mainz/pcl/NormalCloud;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_SampleConsensusModelCylinder_setInputNormals
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
