/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_nat_NativeObject */

#ifndef _Included_de_i3mainz_pcl_nat_NativeObject
#define _Included_de_i3mainz_pcl_nat_NativeObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_nat_NativeObject
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_nat_NativeObject_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
