/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_Point3dColor */

#ifndef _Included_de_i3mainz_pcl_Point3dColor
#define _Included_de_i3mainz_pcl_Point3dColor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_Point3dColor
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3dColor_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3dColor
 * Method:    getR
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_i3mainz_pcl_Point3dColor_getR
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3dColor
 * Method:    setR
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3dColor_setR
  (JNIEnv *, jobject, jshort);

/*
 * Class:     de_i3mainz_pcl_Point3dColor
 * Method:    getG
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_i3mainz_pcl_Point3dColor_getG
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3dColor
 * Method:    setG
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3dColor_setG
  (JNIEnv *, jobject, jshort);

/*
 * Class:     de_i3mainz_pcl_Point3dColor
 * Method:    getB
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_i3mainz_pcl_Point3dColor_getB
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3dColor
 * Method:    setB
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3dColor_setB
  (JNIEnv *, jobject, jshort);

/*
 * Class:     de_i3mainz_pcl_Point3dColor
 * Method:    getRGB
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_i3mainz_pcl_Point3dColor_getRGB
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
