/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_Point3d */

#ifndef _Included_de_i3mainz_pcl_Point3d
#define _Included_de_i3mainz_pcl_Point3d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_Point3d
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3d_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3d
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3d_dispose
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3d
 * Method:    getX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_i3mainz_pcl_Point3d_getX
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3d
 * Method:    setX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3d_setX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_i3mainz_pcl_Point3d
 * Method:    getY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_i3mainz_pcl_Point3d_getY
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3d
 * Method:    setY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3d_setY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_i3mainz_pcl_Point3d
 * Method:    getZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_i3mainz_pcl_Point3d_getZ
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point3d
 * Method:    setZ
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point3d_setZ
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
