/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_Point2d */

#ifndef _Included_de_i3mainz_pcl_Point2d
#define _Included_de_i3mainz_pcl_Point2d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_Point2d
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point2d_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point2d
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point2d_dispose
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point2d
 * Method:    getX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_i3mainz_pcl_Point2d_getX
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point2d
 * Method:    setX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point2d_setX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_i3mainz_pcl_Point2d
 * Method:    getY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_i3mainz_pcl_Point2d_getY
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_Point2d
 * Method:    setY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_Point2d_setY
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
