/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_PointCloud3dColorN */

#ifndef _Included_de_i3mainz_pcl_PointCloud3dColorN
#define _Included_de_i3mainz_pcl_PointCloud3dColorN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_PointCloud3dColorN
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3dColorN_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3dColorN
 * Method:    nGet
 * Signature: (ILde/i3mainz/pcl/Point3dColorN;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3dColorN_nGet
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3dColorN
 * Method:    add
 * Signature: (Lde/i3mainz/pcl/Point3dColorN;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3dColorN_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3dColorN
 * Method:    remove
 * Signature: (Lde/i3mainz/pcl/Point3dColorN;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3dColorN_remove
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3dColorN
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3dColorN_clear
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3dColorN
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_i3mainz_pcl_PointCloud3dColorN_size
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3dColorN
 * Method:    isOrganized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_i3mainz_pcl_PointCloud3dColorN_isOrganized
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
