/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_PointCloud3dColor */

#ifndef _Included_de_i3mainz_pcl_PointCloud3dColor
#define _Included_de_i3mainz_pcl_PointCloud3dColor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_PointCloud3dColor
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3dColor_alloc
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3dColor
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3dColor_dispose
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3dColor
 * Method:    nGet
 * Signature: (ILde/i3mainz/pcl/Point3dColor;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3dColor_nGet
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3dColor
 * Method:    add
 * Signature: (Lde/i3mainz/pcl/Point3dColor;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3dColor_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3dColor
 * Method:    remove
 * Signature: (Lde/i3mainz/pcl/Point3dColor;)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3dColor_remove
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3dColor
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_PointCloud3dColor_clear
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3dColor
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_i3mainz_pcl_PointCloud3dColor_size
  (JNIEnv *, jobject);

/*
 * Class:     de_i3mainz_pcl_PointCloud3dColor
 * Method:    isOrganized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_i3mainz_pcl_PointCloud3dColor_isOrganized
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
