/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_i3mainz_pcl_io_Cloud3DCExporter */

#ifndef _Included_de_i3mainz_pcl_io_Cloud3DCExporter
#define _Included_de_i3mainz_pcl_io_Cloud3DCExporter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_i3mainz_pcl_io_Cloud3DCExporter
 * Method:    nExportPCD
 * Signature: (Ljava/lang/String;Lde/i3mainz/pcl/PointCloud3DC;Z)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_io_Cloud3DCExporter_nExportPCD
  (JNIEnv *, jobject, jstring, jobject, jboolean);

/*
 * Class:     de_i3mainz_pcl_io_Cloud3DCExporter
 * Method:    nExportPLY
 * Signature: (Ljava/lang/String;Lde/i3mainz/pcl/PointCloud3DC;Z)V
 */
JNIEXPORT void JNICALL Java_de_i3mainz_pcl_io_Cloud3DCExporter_nExportPLY
  (JNIEnv *, jobject, jstring, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
