/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pcl_PointXYZRGB */

#ifndef _Included_pcl_PointXYZRGB
#define _Included_pcl_PointXYZRGB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pcl_PointXYZRGB
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pcl_PointXYZRGB_alloc
  (JNIEnv *, jobject);

/*
 * Class:     pcl_PointXYZRGB
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pcl_PointXYZRGB_dispose
  (JNIEnv *, jobject);

/*
 * Class:     pcl_PointXYZRGB
 * Method:    getR
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_pcl_PointXYZRGB_getR
  (JNIEnv *, jobject);

/*
 * Class:     pcl_PointXYZRGB
 * Method:    getG
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_pcl_PointXYZRGB_getG
  (JNIEnv *, jobject);

/*
 * Class:     pcl_PointXYZRGB
 * Method:    getB
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_pcl_PointXYZRGB_getB
  (JNIEnv *, jobject);

/*
 * Class:     pcl_PointXYZRGB
 * Method:    getRGB
 * Signature: ()J
 */
JNIEXPORT jfloat JNICALL Java_pcl_PointXYZRGB_getRGB
  (JNIEnv *, jobject);

/*
 * Class:     pcl_PointXYZRGB
 * Method:    setR
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_pcl_PointXYZRGB_setR
  (JNIEnv *, jobject, jshort);

/*
 * Class:     pcl_PointXYZRGB
 * Method:    setG
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_pcl_PointXYZRGB_setG
  (JNIEnv *, jobject, jshort);

/*
 * Class:     pcl_PointXYZRGB
 * Method:    setB
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_pcl_PointXYZRGB_setB
  (JNIEnv *, jobject, jshort);

/*
 * Class:     pcl_PointXYZRGB
 * Method:    setRGB
 * Signature: (SSS)V
 */
JNIEXPORT void JNICALL Java_pcl_PointXYZRGB_setRGB
  (JNIEnv *, jobject, jshort, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
