/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pcl_PointXYZ */

#ifndef _Included_pcl_PointXYZ
#define _Included_pcl_PointXYZ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pcl_PointXYZ
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pcl_PointXYZ_alloc
  (JNIEnv *, jobject);

/*
 * Class:     pcl_PointXYZ
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pcl_PointXYZ_dispose
  (JNIEnv *, jobject);

/*
 * Class:     pcl_PointXYZ
 * Method:    getX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_pcl_PointXYZ_getX
  (JNIEnv *, jobject);

/*
 * Class:     pcl_PointXYZ
 * Method:    getY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_pcl_PointXYZ_getY
  (JNIEnv *, jobject);

/*
 * Class:     pcl_PointXYZ
 * Method:    getZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_pcl_PointXYZ_getZ
  (JNIEnv *, jobject);

/*
 * Class:     pcl_PointXYZ
 * Method:    setX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_pcl_PointXYZ_setX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     pcl_PointXYZ
 * Method:    setY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_pcl_PointXYZ_setY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     pcl_PointXYZ
 * Method:    setZ
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_pcl_PointXYZ_setZ
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     pcl_PointXYZ
 * Method:    setCoordinates
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_pcl_PointXYZ_setCoordinates
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
