/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vmoglan_pcl_SampleConsensusModelPlane */

#ifndef _Included_com_vmoglan_pcl_SampleConsensusModelPlane
#define _Included_com_vmoglan_pcl_SampleConsensusModelPlane
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vmoglan_pcl_SampleConsensusModelPlane
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vmoglan_pcl_SampleConsensusModelPlane_alloc
  (JNIEnv *, jobject);

/*
 * Class:     com_vmoglan_pcl_SampleConsensusModelPlane
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vmoglan_pcl_SampleConsensusModelPlane_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
