/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_vmoglan_pcljava_NormalCloud */

#ifndef _Included_io_github_vmoglan_pcljava_NormalCloud
#define _Included_io_github_vmoglan_pcljava_NormalCloud
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_vmoglan_pcljava_NormalCloud
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_NormalCloud_alloc(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_NormalCloud
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_NormalCloud_dispose(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_NormalCloud
 * Method:    nGet
 * Signature: (ILde/i3mainz/pcl/Normal;)V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_NormalCloud_nGet(JNIEnv *, jobject, jint, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_NormalCloud
 * Method:    add
 * Signature: (Lde/i3mainz/pcl/Normal;)V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_NormalCloud_add(JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_NormalCloud
 * Method:    remove
 * Signature: (Lde/i3mainz/pcl/Normal;)V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_NormalCloud_remove(JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_NormalCloud
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_NormalCloud_clear(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_NormalCloud
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_vmoglan_pcljava_NormalCloud_size(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_NormalCloud
 * Method:    isOrganized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_vmoglan_pcljava_NormalCloud_isOrganized(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
