/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_vmoglan_pcljava_Normal */

#ifndef _Included_io_github_vmoglan_pcljava_Normal
#define _Included_io_github_vmoglan_pcljava_Normal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_vmoglan_pcljava_Normal
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_Normal_alloc(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_Normal
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_Normal_dispose(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_Normal
 * Method:    getX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_io_github_vmoglan_pcljava_Normal_getX(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_Normal
 * Method:    setX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_Normal_setX(JNIEnv *, jobject, jfloat);

/*
 * Class:     io_github_vmoglan_pcljava_Normal
 * Method:    getY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_io_github_vmoglan_pcljava_Normal_getY(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_Normal
 * Method:    setY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_Normal_setY(JNIEnv *, jobject, jfloat);

/*
 * Class:     io_github_vmoglan_pcljava_Normal
 * Method:    getZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_io_github_vmoglan_pcljava_Normal_getZ(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_Normal
 * Method:    setZ
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_Normal_setZ(JNIEnv *, jobject, jfloat);

/*
 * Class:     io_github_vmoglan_pcljava_Normal
 * Method:    getCurvature
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_io_github_vmoglan_pcljava_Normal_getCurvature(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
