/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_vmoglan_pcljava_Point2d */

#ifndef _Included_io_github_vmoglan_pcljava_Point2d
#define _Included_io_github_vmoglan_pcljava_Point2d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_vmoglan_pcljava_Point2d
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_Point2d_alloc(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_Point2d
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_Point2d_dispose(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_Point2d
 * Method:    getX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_io_github_vmoglan_pcljava_Point2d_getX(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_Point2d
 * Method:    setX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_Point2d_setX(JNIEnv *, jobject, jfloat);

/*
 * Class:     io_github_vmoglan_pcljava_Point2d
 * Method:    getY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_io_github_vmoglan_pcljava_Point2d_getY(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_Point2d
 * Method:    setY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_Point2d_setY(JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
