/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_vmoglan_pcljava_io_PointCloud3dReader */

#ifndef _Included_io_github_vmoglan_pcljava_io_PointCloud3dReader
#define _Included_io_github_vmoglan_pcljava_io_PointCloud3dReader
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     io_github_vmoglan_pcljava_io_PointCloud3dReader
 * Method:    readPCD
 * Signature: (Ljava/lang/String;Lde/i3mainz/pcl/PointCloud3d;)V
 */
  JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_io_PointCloud3dReader_readPCD(JNIEnv *, jobject, jstring, jobject);

  /*
 * Class:     io_github_vmoglan_pcljava_io_PointCloud3dReader
 * Method:    readPLY
 * Signature: (Ljava/lang/String;Lde/i3mainz/pcl/PointCloud3d;)V
 */
  JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_io_PointCloud3dReader_readPLY(JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
