/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_vmoglan_pcljava_SampleConsensusModel */

#ifndef _Included_io_github_vmoglan_pcljava_SampleConsensusModel
#define _Included_io_github_vmoglan_pcljava_SampleConsensusModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_vmoglan_pcljava_SampleConsensusModel
 * Method:    setInputCloud
 * Signature: (Lde/i3mainz/pcl/PointCloud3d;)V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_SampleConsensusModel_setInputCloud(JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_SampleConsensusModel
 * Method:    getSampleSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_vmoglan_pcljava_SampleConsensusModel_getSampleSize(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_SampleConsensusModel
 * Method:    computeVariance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_io_github_vmoglan_pcljava_SampleConsensusModel_computeVariance(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
