/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_vmoglan_pcljava_SampleConsensusModelStick */

#ifndef _Included_io_github_vmoglan_pcljava_SampleConsensusModelStick
#define _Included_io_github_vmoglan_pcljava_SampleConsensusModelStick
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_vmoglan_pcljava_SampleConsensusModelStick
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_SampleConsensusModelStick_alloc(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_SampleConsensusModelStick
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_SampleConsensusModelStick_dispose(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
