/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_vmoglan_pcljava_RandomSampleConsensus */

#ifndef _Included_io_github_vmoglan_pcljava_RandomSampleConsensus
#define _Included_io_github_vmoglan_pcljava_RandomSampleConsensus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_vmoglan_pcljava_RandomSampleConsensus
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_RandomSampleConsensus_alloc(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_RandomSampleConsensus
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_RandomSampleConsensus_dispose(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_RandomSampleConsensus
 * Method:    computeModel
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_vmoglan_pcljava_RandomSampleConsensus_computeModel(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
