/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_vmoglan_pcljava_SampleConsensusModelPlane */

#ifndef _Included_io_github_vmoglan_pcljava_SampleConsensusModelPlane
#define _Included_io_github_vmoglan_pcljava_SampleConsensusModelPlane
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_vmoglan_pcljava_SampleConsensusModelPlane
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_SampleConsensusModelPlane_alloc(JNIEnv *, jobject);

/*
 * Class:     io_github_vmoglan_pcljava_SampleConsensusModelPlane
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_SampleConsensusModelPlane_dispose(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
