/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_vmoglan_pcljava_NormalEstimation */

#ifndef _Included_io_github_vmoglan_pcljava_NormalEstimation
#define _Included_io_github_vmoglan_pcljava_NormalEstimation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_vmoglan_pcljava_NormalEstimation
 * Method:    compute
 * Signature: (Lde/i3mainz/pcl/PointCloud3d;FLde/i3mainz/pcl/NormalCloud;)V
 */
JNIEXPORT void JNICALL Java_io_github_vmoglan_pcljava_NormalEstimation_compute(JNIEnv *, jobject, jobject, jfloat, jobject);

#ifdef __cplusplus
}
#endif
#endif
