/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_vmoglan_pcljava_visualization_Visualizer3d */

#ifndef _Included_io_github_vmoglan_pcljava_visualization_Visualizer3d
#define _Included_io_github_vmoglan_pcljava_visualization_Visualizer3d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_vmoglan_pcljava_visualization_Visualizer3d
 * Method:    addPointCloud
 * Signature: (Lde/i3mainz/pcl/PointCloud;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_vmoglan_pcljava_visualization_Visualizer3d_addPointCloud(JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     io_github_vmoglan_pcljava_visualization_Visualizer3d
 * Method:    addPointCloudNormals
 * Signature: (Lde/i3mainz/pcl/PointCloud;Lde/i3mainz/pcl/NormalCloud;IFLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_vmoglan_pcljava_visualization_Visualizer3d_addPointCloudNormals(JNIEnv *, jobject, jobject, jobject, jint, jfloat, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
