/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_vmoglan_pcljava_visualization_Visualizer3d */

#ifndef _Included_com_github_vmoglan_pcljava_visualization_Visualizer3d
#define _Included_com_github_vmoglan_pcljava_visualization_Visualizer3d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_vmoglan_pcljava_visualization_Visualizer3d
 * Method:    addPointCloud
 * Signature: (Lcom/github/vmoglan/pcljava/PointCloud;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_vmoglan_pcljava_visualization_Visualizer3d_addPointCloud(JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_github_vmoglan_pcljava_visualization_Visualizer3d
 * Method:    addPointCloudNormals
 * Signature: (Lcom/github/vmoglan/pcljava/PointCloud;Lcom/github/vmoglan/pcljava/NormalCloud;IFLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_vmoglan_pcljava_visualization_Visualizer3d_addPointCloudNormals(JNIEnv *, jobject, jobject, jobject, jint, jfloat, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
