/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_vmoglan_pcljava_io_PointCloud3dReaderPcd */

#ifndef _Included_com_github_vmoglan_pcljava_io_PointCloud3dReaderPcd
#define _Included_com_github_vmoglan_pcljava_io_PointCloud3dReaderPcd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_vmoglan_pcljava_io_PointCloud3dReaderPcd
 * Method:    read
 * Signature: (Ljava/lang/String;Lcom/github/vmoglan/pcljava/PointCloud3d;)V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_io_PointCloud3dReaderPcd_read
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
