/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_vmoglan_pcljava_SampleConsensusModelLine */

#ifndef _Included_com_github_vmoglan_pcljava_SampleConsensusModelLine
#define _Included_com_github_vmoglan_pcljava_SampleConsensusModelLine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_vmoglan_pcljava_SampleConsensusModelLine
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_SampleConsensusModelLine_alloc(JNIEnv *, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_SampleConsensusModelLine
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_SampleConsensusModelLine_dispose(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
