/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_vmoglan_pcljava_NormalEstimation */

#ifndef _Included_com_github_vmoglan_pcljava_NormalEstimation
#define _Included_com_github_vmoglan_pcljava_NormalEstimation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_vmoglan_pcljava_NormalEstimation
 * Method:    compute
 * Signature: (Lcom/github/vmoglan/pcljava/PointCloud3d;FLcom/github/vmoglan/pcljava/NormalCloud;)V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_NormalEstimation_compute(JNIEnv *, jobject, jobject, jfloat, jobject);

#ifdef __cplusplus
}
#endif
#endif
