/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_vmoglan_pcljava_io_PointCloud3dWriterPcd */

#ifndef _Included_com_github_vmoglan_pcljava_io_PointCloud3dWriterPcd
#define _Included_com_github_vmoglan_pcljava_io_PointCloud3dWriterPcd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_vmoglan_pcljava_io_PointCloud3dWriterPcd
 * Method:    write
 * Signature: (Lcom/github/vmoglan/pcljava/PointCloud3d;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_io_PointCloud3dWriterPcd_write
  (JNIEnv *, jobject, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
