/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_vmoglan_pcljava_SampleConsensusModel */

#ifndef _Included_com_github_vmoglan_pcljava_SampleConsensusModel
#define _Included_com_github_vmoglan_pcljava_SampleConsensusModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_vmoglan_pcljava_SampleConsensusModel
 * Method:    setInputCloud
 * Signature: (Lcom/github/vmoglan/pcljava/PointCloud3d;)V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_SampleConsensusModel_setInputCloud(JNIEnv *, jobject, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_SampleConsensusModel
 * Method:    getSampleSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_vmoglan_pcljava_SampleConsensusModel_getSampleSize(JNIEnv *, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_SampleConsensusModel
 * Method:    computeVariance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_github_vmoglan_pcljava_SampleConsensusModel_computeVariance(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
