/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_vmoglan_pcljava_SampleConsensusModelSphere */

#ifndef _Included_com_github_vmoglan_pcljava_SampleConsensusModelSphere
#define _Included_com_github_vmoglan_pcljava_SampleConsensusModelSphere
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_vmoglan_pcljava_SampleConsensusModelSphere
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_SampleConsensusModelSphere_alloc(JNIEnv *, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_SampleConsensusModelSphere
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_SampleConsensusModelSphere_dispose(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
