/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_vmoglan_pcljava_SampleConsensusModelCylinder */

#ifndef _Included_com_github_vmoglan_pcljava_SampleConsensusModelCylinder
#define _Included_com_github_vmoglan_pcljava_SampleConsensusModelCylinder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_vmoglan_pcljava_SampleConsensusModelCylinder
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_SampleConsensusModelCylinder_alloc(JNIEnv *, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_SampleConsensusModelCylinder
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_SampleConsensusModelCylinder_dispose(JNIEnv *, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_SampleConsensusModelCylinder
 * Method:    getNormalDistanceWeight
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_github_vmoglan_pcljava_SampleConsensusModelCylinder_getNormalDistanceWeight(JNIEnv *, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_SampleConsensusModelCylinder
 * Method:    setNormalDistanceWeight
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_SampleConsensusModelCylinder_setNormalDistanceWeight(JNIEnv *, jobject, jdouble);

/*
 * Class:     com_github_vmoglan_pcljava_SampleConsensusModelCylinder
 * Method:    getInputNormals
 * Signature: (Lcom/github/vmoglan/pcljava/NormalCloud;)V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_SampleConsensusModelCylinder_getInputNormals(JNIEnv *, jobject, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_SampleConsensusModelCylinder
 * Method:    setInputNormals
 * Signature: (Lcom/github/vmoglan/pcljava/NormalCloud;)V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_SampleConsensusModelCylinder_setInputNormals(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
