/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_vmoglan_pcljava_NormalCloud */

#ifndef _Included_com_github_vmoglan_pcljava_NormalCloud
#define _Included_com_github_vmoglan_pcljava_NormalCloud
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_vmoglan_pcljava_NormalCloud
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_NormalCloud_alloc(JNIEnv *, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_NormalCloud
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_NormalCloud_dispose(JNIEnv *, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_NormalCloud
 * Method:    at
 * Signature: (ILcom/github/vmoglan/pcljava/Normal;)V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_NormalCloud_at(JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_NormalCloud
 * Method:    add
 * Signature: (Lcom/github/vmoglan/pcljava/Normal;)V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_NormalCloud_add(JNIEnv *, jobject, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_NormalCloud
 * Method:    remove
 * Signature: (Lcom/github/vmoglan/pcljava/Normal;)V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_NormalCloud_remove(JNIEnv *, jobject, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_NormalCloud
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_vmoglan_pcljava_NormalCloud_clear(JNIEnv *, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_NormalCloud
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_vmoglan_pcljava_NormalCloud_size(JNIEnv *, jobject);

/*
 * Class:     com_github_vmoglan_pcljava_NormalCloud
 * Method:    isOrganized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_vmoglan_pcljava_NormalCloud_isOrganized(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
